version: 2.1

git_restore_cache: &git_restore_cache
  restore_cache:
    keys:
      - source-v1-{{ .Branch }}-{{ .Revision }}
      - source-v1-{{ .Branch }}-
      - source-v1-

git_save_cache: &git_save_cache
  save_cache:
    key: source-v1-{{ .Branch }}-{{ .Revision }}
    paths:
      - ".git"

# npm_restore_cache: &npm_restore_cache
#   restore_cache:
#     keys:
#       - npm-v1-{{ checksum "_generator/package-lock.json" }}
#       - npm-v1-

# npm_save_cache: &npm_save_cache
#   save_cache:
#     key: npm-v1-{{ checksum "_generator/package-lock.json" }}
#     paths:
#       - node_modules


jobs:
  build:
    docker:
      - image: 'circleci/node:16'
    steps:
      - *git_restore_cache
      - checkout
      - run: npm ci
      # - *npm_save_cache
      - run: node src/crosspolitic-feed-splitter.js

      - add_ssh_keys:
          fingerprints:
            - "b3:c9:00:4a:21:7f:4e:b0:d8:2f:d1:cd:52:0f:eb:3e"
      - run: git config user.email "josephdykstra@gmail.com"
      - run: git config user.name "ArtskydJ"

      - run: git add .
      - run: git commit -m "Build [skip ci]" || echo "No changes detected"
      - run: git push origin gh-pages
      - *git_save_cache


workflows:
  version: 2
  hourly:
    triggers:
      - schedule:
          cron: "0 * * * *"
          # https://cron.help/#0_*_*_*_*
          filters:
            branches:
              only:
                - gh-pages
    jobs:
      - build

  onpush:
    jobs:
      - build:
          filters:
            branches:
              only:
                - gh-pages

# To validate w/o committing, run `circleci config validate` on the command line
