version: 2.1

git_restore_cache: &git_restore_cache
  restore_cache:
    keys:
      - source-v1-{{ .Branch }}-
      - source-v1-

git_save_cache: &git_save_cache
  save_cache:
    key: source-v1-{{ .Branch }}-
    paths:
      - ".git"

jobs:
  build:
    docker:
      - image: 'circleci/node:16'
    steps:
      - *git_restore_cache
      - checkout
      - run: npm ci
      - run: npm run build

      - add_ssh_keys:
          fingerprints:
            - "b3:c9:00:4a:21:7f:4e:b0:d8:2f:d1:cd:52:0f:eb:3e"
      - run: git config user.email "josephdykstra@gmail.com"
      - run: git config user.name "ArtskydJ"

      - run: git add .
      - run: git commit -m "Build [skip ci]" || echo "No changes detected"
      - run: git push origin gh-pages
      - *git_save_cache


workflows:
  version: 2
  every_six_hours:
    triggers:
      - schedule:
          cron: "25 1,7,13,19 * * *"
          # https://cron.help/#25_1,7,13,19_*_*_*
          filters:
            branches:
              only:
                - gh-pages
    jobs:
      - build

  onpush:
    jobs:
      - build:
          filters:
            branches:
              only:
                - gh-pages

# To validate w/o committing, run `circleci config validate` on the command line
